# Generated by Django 3.2.9 on 2024-02-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='コンピューター名')),
                ('cpu', models.CharField(max_length=20, verbose_name='CPU')),
                ('memory_cap', models.IntegerField(blank=True, default=0, null=True, verbose_name='メモリ容量')),
                ('strage_cap', models.IntegerField(blank=True, default=0, null=True, verbose_name='ストレージ容量')),
                ('os', models.CharField(max_length=20, verbose_name='OS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
    ]
